twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        upload_directory: '%upload.directory.name%'
        app_name: '%app.name%'
        domain_url: '%domain.url%'
        author: '%author%'
        assets_directory_name: '%assets.directory.name%'
        weightsCount: '%weightsCount%'
        supportMail: '%supportMail%'
        favicon_directory_name: '%favicon.directory.name%'
